spring:
  datasource:
    url: jdbc:mysql://13.124.136.91:3306/examplesdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: myo
    password: sonji0211!
  thymeleaf:
#    prefix: classpath:/html/ default?? ????? ??? ??? ????
#    suffix: .fm